import './App.css';
import { Grid, Typography } from '@material-ui/core';
import SelectBy from './components/SelectBy.js';
import Cards from './components/Cards';

function App() {

  const valueFields = [
    {
      value: 1,
      label: 'Portfolio enhancement and expansion'
    },
    {
      value: 2,
      label: 'Efficiency Enhancement'
    },
    {
      value: 3,
      label: 'Network optimisation'
    },
    {
      value: 4,
      label: 'Revenue growth'
    },
    {
      value: 5,
      label: 'Operating cost reductions'
    }
  ];

  const locationFields = [
    {
      value: 'all',
      label: 'All'
    },
    {
      value: 'europe',
      label: 'Europe / UK / Scandinavia'
    },
    {
      value: 'us',
      label: 'US / Canada'
    },
    {
      value: 'asia',
      label: 'Asia Pacific'
    },
    {
      value: 'gloabl',
      label: 'Global'
    },
  ]

  return (
    <div className="App">
      <Grid container>
        <Grid item md={6}>
          <Typography variant="h5">Discover the value generated by bank APIs</Typography>
          <Cards />
        </Grid>
        <Grid item md={6}>
          <Typography variant="h5">Bank API Value Generation Examples</Typography>
          <SelectBy valueFields={valueFields} locationFields={locationFields}/>
        </Grid>
      </Grid>
    </div>
  );
}

export default App;
